version: '3'

services:
  zoo:
    image: zookeeper:3.6.2
    restart: always
    ports:
      - "2181:2181"

  node-1:
    depends_on:
      - zoo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zoo:2181
    ports:
      - "8081:8081"

  node-2:
    depends_on:
      - zoo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zoo:2181
    ports:
      - "8082:8081"

  node-3:
    depends_on:
      - zoo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zoo:2181
    ports:
      - "8083:8081"